# Generated by Django 4.2.8 on 2024-02-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=125)),
                ('last_name', models.CharField(blank=True, max_length=125)),
                ('favorite_team', models.IntegerField(blank=True, choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
