# Generated by Django 4.2.10 on 2024-02-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_usermodel_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
