# Generated by Django 4.2.8 on 2024-02-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
