# Generated by Django 4.2.10 on 2024-02-12 22:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremierLeagueTeamBase',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('team_code', models.PositiveIntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')], db_index=True, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamFixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comp', models.PositiveIntegerField()),
                ('game_week', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)])),
                ('day', models.PositiveIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], db_index=True)),
                ('ground', models.PositiveIntegerField(choices=[(0, 'Home Game'), (1, 'Away Game')], db_index=True)),
                ('result', models.PositiveIntegerField(choices=[(0, 'Win'), (1, 'Lose'), (2, 'Draw')], null=True)),
                ('goals_for', models.PositiveIntegerField(default=None, null=True)),
                ('goals_against', models.PositiveIntegerField(default=None, null=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_fixtures_opponent', to='premier_league.premierleagueteambase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_fixtures_team', to='premier_league.premierleagueteambase')),
            ],
        ),
        migrations.CreateModel(
            name='PremierLeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postition', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('matches_played', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(38)])),
                ('wins', models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(38)])),
                ('losses', models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(38)])),
                ('draws', models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(38)])),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goals_differance', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(114)])),
                ('points_per_match', models.FloatField(default=0)),
                ('expected_goals_for', models.FloatField(default=0)),
                ('expected_goals_against', models.FloatField(default=0)),
                ('expected_goals_differance', models.FloatField(default=0)),
                ('expected_goals_differance_per_ninety', models.FloatField(default=0)),
                ('last_five', models.CharField(max_length=10)),
                ('base_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premier_league.premierleagueteambase')),
            ],
            options={
                'ordering': ['postition'],
            },
        ),
    ]
