# Generated by Django 4.2.10 on 2024-02-10 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremierLeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('team_code', models.PositiveIntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')])),
                ('postition', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('matches_played', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(38)])),
                ('wins', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(38)])),
                ('losses', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(38)])),
                ('draws', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(38)])),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goals_differance', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(114)])),
                ('points_per_match', models.FloatField(default=0)),
                ('expected_goals_for', models.FloatField(default=0)),
                ('expected_goals_against', models.FloatField(default=0)),
                ('expected_goals_differance', models.FloatField(default=0)),
                ('expected_goals_differance_per_ninety', models.FloatField(default=0)),
                ('last_five', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeamFixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.PositiveIntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')])),
                ('date', models.DateField()),
                ('comp', models.PositiveIntegerField()),
                ('game_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)])),
                ('day', models.PositiveIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')])),
                ('ground', models.PositiveIntegerField(choices=[(0, 'Home Game'), (1, 'Away Game')])),
                ('result', models.PositiveIntegerField(choices=[(0, 'Win'), (1, 'Lose')])),
                ('goals_for', models.PositiveIntegerField(default=None, null=True)),
                ('goals_against', models.PositiveIntegerField(default=None, null=True)),
                ('opponent', models.PositiveIntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')])),
            ],
        ),
    ]
