# Generated by Django 4.2.10 on 2024-02-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0002_alter_teamfixtures_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premierleagueteam',
            options={'ordering': ['postition']},
        ),
    ]
