# Generated by Django 4.2.10 on 2024-02-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0004_alter_teamfixtures_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamfixtures',
            name='time',
        ),
    ]
