# Generated by Django 4.2.10 on 2024-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0005_remove_teamfixtures_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfixtures',
            name='time',
            field=models.TimeField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
