# Generated by Django 4.2.10 on 2024-02-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0007_alter_teamfixtures_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamfixtures',
            options={'ordering': ['game_week']},
        ),
    ]
