# Generated by Django 4.2.10 on 2024-02-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('premier_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('nation', models.CharField(max_length=10, null=True)),
                ('position', models.IntegerField(choices=[(0, 'GoalKeeper'), (1, 'Defender'), (3, 'Midfielder'), (4, 'Striker')], db_index=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('matches_played', models.IntegerField(default=0, null=True)),
                ('starts', models.IntegerField(default=0, null=True)),
                ('minutes', models.IntegerField(db_index=True, default=0, null=True)),
                ('nineties', models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True)),
                ('goals', models.IntegerField(db_index=True, default=0, null=True)),
                ('assists', models.IntegerField(db_index=True, default=0, null=True)),
                ('goals_and_assists', models.IntegerField(default=0, null=True)),
                ('none_penalty_goals', models.IntegerField(default=0, null=True)),
                ('penalty_goals', models.IntegerField(db_index=True, default=0, null=True)),
                ('penalties_attempted', models.IntegerField(db_index=True, default=0, null=True)),
                ('yellow_cards', models.IntegerField(db_index=True, default=0, null=True)),
                ('red_cards', models.IntegerField(db_index=True, default=0, null=True)),
                ('saves', models.IntegerField(default=0)),
                ('penalty_saves', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(db_index=True, default=0)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('overall_points', models.IntegerField(default=0)),
                ('game_week_points', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='premier_league.premierleagueteambase')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerIjuriesAndBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(db_index=True, null=True)),
                ('return_data', models.DateField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_info.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='premier_league.premierleagueteambase')),
            ],
        ),
    ]
