# Generated by Django 4.2.10 on 2024-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('nation', models.CharField(max_length=10, null=True)),
                ('position', models.IntegerField(choices=[(0, 'GoalKeeper'), (1, 'Defender'), (3, 'Midfielder'), (4, 'Striker')])),
                ('age', models.IntegerField(default=0, null=True)),
                ('matches_played', models.IntegerField(default=0, null=True)),
                ('starts', models.IntegerField(default=0, null=True)),
                ('minutes', models.IntegerField(default=0, null=True)),
                ('nineties', models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True)),
                ('goals', models.IntegerField(default=0, null=True)),
                ('assists', models.IntegerField(default=0, null=True)),
                ('goals_and_assists', models.IntegerField(default=0, null=True)),
                ('none_penalty_goals', models.IntegerField(default=0, null=True)),
                ('penalty_goals', models.IntegerField(default=0, null=True)),
                ('penalties_attempted', models.IntegerField(default=0, null=True)),
                ('yellow_cards', models.IntegerField(default=0, null=True)),
                ('red_cards', models.IntegerField(default=0, null=True)),
                ('team', models.IntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')])),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('overall_points', models.IntegerField(default=0)),
                ('game_week_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerIjuriesAndBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('team', models.IntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')])),
                ('status', models.IntegerField(null=True)),
                ('return_data', models.DateField(null=True)),
            ],
        ),
    ]
