# Generated by Django 4.2.10 on 2024-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='minutes',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalties_attempted',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalty_goals',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(0, 'GoalKeeper'), (1, 'Defender'), (3, 'Midfielder'), (4, 'Striker')], db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.IntegerField(choices=[(0, 'Arsenal'), (1, 'Aston Villa'), (2, 'Brentford'), (3, 'Brighton'), (4, 'Bournemouth'), (5, 'Burnley'), (6, 'Chelsea'), (7, 'Crystal Palace'), (8, 'Everton'), (9, 'Fulham'), (10, 'Liverpool'), (11, 'Luton Town'), (12, 'Manchester City'), (13, 'Manchester United'), (14, 'Newcastle United'), (15, 'Nottingham Forset'), (16, 'Sheffield United'), (17, 'Tottenham Hotspur'), (18, 'Westham United'), (19, 'Wolverhamption Wanderers')], db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
