# Generated by Django 4.2.10 on 2024-02-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='middle_name',
        ),
    ]
