# Generated by Django 4.2.10 on 2024-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_info', '0002_alter_player_assists_alter_player_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='penalty_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
