# Generated by Django 4.2.9 on 2024-02-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_info', '0005_playerijuriesandbans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerijuriesandbans',
            old_name='fist_name',
            new_name='fisrt_name',
        ),
    ]
