# Generated by Django 4.2.9 on 2024-02-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_info', '0006_rename_fist_name_playerijuriesandbans_fisrt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerijuriesandbans',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
