# Generated by Django 4.2.10 on 2024-02-12 22:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premier_league', '0001_initial'),
        ('player_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_points', models.IntegerField(db_index=True, default=0)),
                ('overall_rank', models.IntegerField(db_index=True, default=0)),
                ('free_transfers', models.IntegerField(default=0)),
                ('game_week_transfers_made', models.IntegerField(default=0)),
                ('bank', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('team_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bench_boost', models.BooleanField(default=True)),
                ('free_hit', models.BooleanField(default=True)),
                ('triple_captin', models.BooleanField(default=True)),
                ('wild_card', models.BooleanField(default=True)),
                ('favorite_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='premier_league.premierleagueteambase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(38)])),
                ('points_cost', models.IntegerField(default=0)),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_transfer_player_in', to='player_info.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_transfer_player_out', to='player_info.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameWeekTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, db_index=True, default=0)),
                ('game_week', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(38)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_week_team_team', to='team_management.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameWeekPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(0, 'GoalKeeper'), (1, 'Defender'), (3, 'Midfielder'), (4, 'Striker')])),
                ('starter', models.BooleanField(db_index=True, default=False)),
                ('benched_order', models.IntegerField(blank=True, choices=[(0, 'Goolkeeper Bench'), (1, 'First Choice'), (2, 'Second Choice'), (3, 'Third Choice')], default=None, null=True)),
                ('points', models.IntegerField(blank=True, db_index=True, default=0)),
                ('game_week_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_week_player_game_week_team', to='team_management.gameweekteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_info.player')),
            ],
        ),
    ]
