# Generated by Django 4.2.9 on 2024-02-06 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameWeekPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(db_index=True, default=False)),
                ('benched_order', models.IntegerField(choices=[(0, 'Goolkeeper Bench'), (1, 'First Choice'), (2, 'Second Choice'), (3, 'Third Choice')], default=None, null=True)),
                ('points', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameWeekTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_index=True, default=0)),
                ('game_week', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(38)])),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(38)])),
                ('points_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_points', models.IntegerField(db_index=True, default=0)),
                ('overall_rank', models.IntegerField(db_index=True, default=0)),
                ('free_transfers', models.IntegerField(default=0)),
                ('game_week_transfers_made', models.IntegerField(default=0)),
                ('bank', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('team_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bench_boost', models.BooleanField(default=True)),
                ('free_hit', models.BooleanField(default=True)),
                ('triple_captin', models.BooleanField(default=True)),
                ('wild_card', models.BooleanField(default=True)),
            ],
        ),
    ]
