# Generated by Django 4.2.10 on 2024-02-07 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_info', '0001_initial'),
        ('team_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playertransfer',
            name='player_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_transfer_player_in', to='player_info.player'),
        ),
        migrations.AddField(
            model_name='playertransfer',
            name='player_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_transfer_player_out', to='player_info.player'),
        ),
        migrations.AddField(
            model_name='playertransfer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team'),
        ),
        migrations.AddField(
            model_name='gameweekteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team'),
        ),
        migrations.AddField(
            model_name='gameweekplayer',
            name='game_week_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team_management.gameweekteam'),
        ),
        migrations.AddField(
            model_name='gameweekplayer',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_info.player'),
        ),
    ]
