# Generated by Django 4.2.10 on 2024-03-01 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0002_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweekplayer',
            name='index',
            field=models.PositiveIntegerField(default=None, unique=True, validators=[django.core.validators.MaxValueValidator(14)]),
            preserve_default=False,
        ),
    ]
