# Generated by Django 4.2.10 on 2024-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_alter_gameweekplayer_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweekplayer',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
