# Generated by Django 4.2.10 on 2024-02-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0004_alter_gameweekplayer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweekplayer',
            name='game_week_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.gameweekteam'),
        ),
    ]
