# Generated by Django 4.2.10 on 2024-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0005_alter_gameweekplayer_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='made_first_team',
            field=models.BooleanField(default=False),
        ),
    ]
