# Generated by Django 4.2.10 on 2024-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0005_alter_gameweekplayer_game_week_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweekplayer',
            name='position',
            field=models.IntegerField(choices=[(0, 'GoalKeeper'), (1, 'Defender'), (3, 'Midfielder'), (4, 'Striker')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameweekplayer',
            name='benched_order',
            field=models.IntegerField(blank=True, choices=[(0, 'Goolkeeper Bench'), (1, 'First Choice'), (2, 'Second Choice'), (3, 'Third Choice')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gameweekplayer',
            name='points',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='gameweekteam',
            name='points',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
