# Generated by Django 4.2.10 on 2024-02-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=125)),
                ('num_of_players', models.PositiveIntegerField(default=0)),
                ('is_h2h', models.BooleanField(db_index=True, default=False)),
                ('admin', models.ManyToManyField(related_name='league_admin', to='team_management.team')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_owner', to='team_management.team')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('game_week_points', models.PositiveIntegerField(db_index=True, default=0)),
                ('overall_points', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_management.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='H2HLeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(db_index=True, default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('game_week_points', models.PositiveIntegerField(db_index=True, default=0)),
                ('score', models.PositiveIntegerField(db_index=True, default=0)),
                ('overall_points', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_management.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
