# Generated by Django 4.2.10 on 2024-02-14 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h2hleagueteam',
            options={'ordering': ['-overall_points']},
        ),
        migrations.AlterModelOptions(
            name='leagueteam',
            options={'ordering': ['-overall_points']},
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='draws',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='game_week_points',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='games_played',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='losses',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='overall_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='score',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='h2hleagueteam',
            name='wins',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='leagueteam',
            name='game_week_points',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='leagueteam',
            name='overall_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='leagueteam',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
