# Generated by Django 4.2.10 on 2024-02-16 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0002_alter_h2hleagueteam_options_alter_leagueteam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='allow_post_create_entry',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='starting_game_week',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)]),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
