# Generated by Django 4.2.10 on 2024-02-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0003_league_allow_post_create_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h2hleagueteam',
            options={'ordering': ['-score']},
        ),
    ]
