# Generated by Django 4.2.10 on 2024-02-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0004_alter_h2hleagueteam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h2hleagueteam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leagueteam',
            options={},
        ),
    ]
