# Generated by Django 4.2.10 on 2024-03-07 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0005_alter_h2hleagueteam_options_alter_leagueteam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueteam',
            name='last_position',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
